### ISSUE TITLE
exe file

### ISSUE THREAD

**Issue by xciron** [jramshur/HRVAS#1]
I downloaded MCR but I'm not sure how to set it up based on the installation instructions. My download did not include an exe file.

**Comment by lrluna66** [comment]
I am having the same problem. No exe file in the unzipped folder.

**Comment by jramshur** [comment]
Sorry. I forgot to update the Wiki. The MCR is very large so I will leave it on the original Sourceforge site. You can download all the Standalone files there: https://sourceforge.net/projects/hrvas/files/Standalone%20Application/

**Comment by lrluna66** [comment]
Thank you!

**Comment by xciron** [comment]
Thanks. I had trouble installing and launching, but this was fixed when I deleted everything and did a clean install. Cheers!
