### ISSUE TITLE
Ouput is not Displayed

### ISSUE THREAD

**Issue by akanksha785** [jramshur/HRVAS#11]
Hi,

I am trying to run HRVAS software using text file(.txt) format as well as ibi file. However, output results are not seen. 
Kindly look into this matter
![Capture_1](https://user-images.githubusercontent.com/60707511/111706760-d3d8ff00-8810-11eb-9ff2-db1fc3cee9d7.PNG)

**Comment by alinooriyan** [comment]
I think its because of unsupported formats

**Comment by jramshur** [comment]
Unsupported data format in the file is likely the issue. See text below from the Wiki in regards to the input files. Also, have a look at one of the sample files in the repository to see if it matches the data format you are using.

"HRVAS can read inter-beat interval files (.ibi) and text files (.txt), both of which are ASCII files. The expected data format must have one or two columns (comma separated). If one column is used, this column must represent IBI/RR values in units of seconds. If two columns are used, the first column represents time in units of seconds. The second column represents IBI/RR values in units of seconds."
