### ISSUE TITLE
GUI Error in Matlab 2014 and 2016

### ISSUE THREAD

**Issue by tomlehmann** [jramshur/HRVAS#2]
```
Error using hguitab
While setting the 'Position' property of Tab:
You cannot set the read-only property 'Position' of Tab.

Error in usev0tab (line 13)
Error in uitab (line 28)
h = usev0tab(varargin{:});

Error in HRVAS_r2010b (line 748)
    h.tab1 = uitab('parent',h.tabgroup, 'title', 'Time Domain', ...
Error in main (line 4)
HRVAS_r2010b
```

This is displayed in Matlab console after running the main.m. The GUI loads but is incomplete. I tried this on two different Macs with Matlab 2014 and 2016.

![incompletegui](https://cloud.githubusercontent.com/assets/2663021/20905013/640b55fa-bb42-11e6-989d-56f7ba5b625a.png)

**Comment by radosi** [comment]
I have the same problem ... anyone?

**Comment by jramshur** [comment]
It's an issue with how MATLAB changed the implementation of uitab. I will be trying to fix this next week.

**Comment by radosi** [comment]
Thanks. Also I would like to ask you is it possible to contribute in order to make loading of ECG file in the engine ?
 for example 1 or more channels with 125/250 samples in second

**Comment by manidmandimandi** [comment]
I'm also having the identical issue. I ran the main.m on a MATLAB2016a version.
Thanks!
