### ISSUE TITLE
Stuck when running 24h data

### ISSUE THREAD

**Issue by anate** [jramshur/HRVAS#8]
When I run large files of data such as synthethic_rr.txt that corresponds to 24h data, the GUI gets stuck sometimes at Non-linear or Time-Freq.
![stuck_gui_status](https://user-images.githubusercontent.com/25034977/33526939-39d7e916-d86e-11e7-8b95-b2ed3f7b3f7a.png)
![stuck_problem_report](https://user-images.githubusercontent.com/25034977/33526940-3a251c22-d86e-11e7-84cd-00b3a8feb5e7.png)

**Comment by jramshur** [comment]
Do you know how much RAM you are using? Can you watch the RAM usage before and after running HRVAS?

**Comment by jramshur** [comment]
@anate Did you have any update on this issue?

**Comment by anate** [comment]
@jramshur
 (Apologising for the late reply/update)
Seems like the issue occurs on systems with low RAM, such as 4GB.
